/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2013-11-17 00:29:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import quizsite.*;
import quizsite.DBConnection;
import quizsite.History;
import quizsite.User;
import quizsite.Mail;
import java.util.*;
import java.sql.ResultSet;
import java.text.*;

public final class Home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write(" \n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");

User currUser = (User) session.getAttribute("user");
ArrayList<Mail> mails = currUser.getMails();
ArrayList<History> histories = currUser.getHistories();
ArrayList<User> friends = currUser.getFriendsList();
DBConnection con = (DBConnection) session.getAttribute("connection");
if(con == null) {
	con = new DBConnection();
	session.setAttribute("connection", con);
}
int numNewMail = User.getNumNewMailById(currUser.getId(), con);
User.setNumNewMailToZeroById(currUser.getId(), con);

      out.write("\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/QuizWebsite/Home.css\" type=\"text/css\">\n");
      out.write("<title>Home</title>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("<p class=\"logout\"><a href=\"Login.html\">Logout</a></p>\n");
      out.write("<h3>Hello, ");
      out.print( currUser.getUsername() );
      out.write("! Welcome to our quiz website!</h3>\n");
      out.write("\n");
      out.write("<div class=\"msg\">\n");
      out.write("<p class=\"block_title\">Mails Received\n");
 if(numNewMail != 0) {
	out.println("<span class='new_mail_notice'>(" + numNewMail + " new mails)</span>");
}

      out.write("\n");
      out.write("</p>\n");

for(int i = 0; i < numNewMail; i++) {
	int fromId = mails.get(i).getFromId();
	String fromUsername = User.getUsernameById(fromId, con);
	if(mails.get(i).getType() == Mail.FRIEND_REQ) {
		out.println("<p class='each_mail'>From <a href=\"User.jsp?id=" + fromId + "\">" + fromUsername + "</a>: </p><table><tr><td>Friend request: </td><td><form action=\"FriendServlet\" method=\"post\"><input type=\"submit\" value=\"Confirm\"/><input type=\"hidden\" name=\"addFriendId\" value=\"" + fromId + "\" /></form></td></tr></table>");
	} else if(mails.get(i).getType() == Mail.CHALLENGE) {
		out.println("<p class='each_mail'>From <a href=\"User.jsp?id=" + fromId + "\">" + fromUsername + "</a>: </p><p class='mail_msg'>Challenge url link: " + mails.get(i).getContent() + "</p>");
	} else {
		out.println("<p class='each_mail'>From <a href=\"User.jsp?id=" + fromId + "\">" + fromUsername + "</a>: </p><p class='mail_msg'>Message: " + mails.get(i).getContent() + "</p>");
	}
}

      out.write("\n");
      out.write("<a href=\"AllMails.jsp\">Check All Mails &gt;&gt;</a>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"lists\">\n");
      out.write("<div class=\"pop_quiz list_block\">\n");
      out.write("<p class=\"block_title\">Pop Quizzes</p>\n");
      out.write("</div>\n");
      out.write("<div class=\"recent_created_quiz list_block\">\n");
      out.write("<p class=\"block_title\">Recently Created Quizzes</p>\n");
      out.write("</div>\n");
      out.write("<div class=\"taken_quiz_activity list_block\">\n");
      out.write("<p class=\"block_title\">Recently Quizzes Taken</p>\n");
      out.write("</div>\n");
      out.write("<div class=\"recent_self_created_quiz list_block\">\n");
      out.write("<p class=\"block_title\">Quizzes Created by You</p>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"friends_activity\">\n");
      out.write("<p class=\"block_title\">Friends Activities</p>\n");

for(int i = 0; i < friends.size(); i++) {
	User f = friends.get(i);
	out.println("<p class='each_history'>Your friend " + f.getUsername() + ". </p>");
}

      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"user_history\">\n");
      out.write("<p class=\"block_title\">History</p>\n");

for(int i = 0; i < histories.size(); i++) {
	History h = histories.get(i);
	out.println("<p class='each_history'>Take quiz " + h.getQuizId() + ", using " + h.getElapsedTime() + ", score is " + h.getScore() + ", at " + h.getFinishAt() + ". </p>");
}

      out.write("\n");
      out.write("<a href=\"AllHistories.jsp\">Check History &gt;&gt;</a>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<form action=\"QuizServlet\" method = \"post\">\n");
      out.write("<input type=\"submit\" value = \"Create quiz\" />\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("<!--<form action=\"HistoryServlet\" method=\"post\">\n");
      out.write("<input type=\"submit\" value=\"Create History\"/>\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("--><!--<form action=\"FriendServlet\" method=\"post\">\n");
      out.write("<input type=\"submit\" value=\"Create Friend\"/>\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("<form action=\"MailServlet\" method=\"post\">\n");
      out.write("<input type=\"submit\" value=\"Create Mail\"/>\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("--></body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
